token:
  expiration_time: 864000000 
  secret: '{cipher}AYA6pTjNXwivoA1IJB/NuetmjbNherEnjX/94/7FxPiYKh2VVb49qC6fmAA49C2lFGWa9uaGjKwHHn7X1VCaJ3qasbk9kbfeora2YjaJIa4izUJUPuj6bpeJhM6ix5mBwJMYBY0dBSExBGRZo3zAEw22Gb2p47jEPwjug9jc+mbxjZQRH441MJQtGflE5WcuH2U2WxzkO/zwfTi/C8EgTrnHltNcSNmy4PY9o6hbMYbuLXq+rbbutD3TM2/0ONd7zCYd2rOd86lJZDAopWZblQfQYOJZHtkyeghOUl18bVNpVh5tA4vj6hV8o7YEcv591337xLLLO78zH/P8NRQbnypO6Mzk+4wIfWKL71LY/WyjKnmpzqw/tmtH3f39J/esi/RzfFUKjPS4ldI4M7xhglR2kF0IIop9eh2rvCN9T/Zadh1588WjhMhXustUL54pFvrN5/hjYEBrwzhzEAh1az9S+YVtPQW7YVD1pMgzi3T2h0ywQI3mEIz7m7a/TcUXrbCZDgXiYt0uvDpG56rkOIznptvBIuE6GHb98vLW1TKdfnl4CzHfCa0l1oh2VBNuaWwJsWNSgsVf8/ONCfh9qlqmqQhmh1gKCtcVk5i40owquoeJy1cTuhTRO+Y2Ruc1+u8='

gateway:
  ip: 172.18.0.1
